---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: build.sh
      - name: Run
        run: |
          cd dist
          tar zcf Ice-3.6.5-rockylinux9-x86_64.tar.gz Ice-3.6.5
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/*.tar.gz
          if-no-files-found: error
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.tar.gz
